version: '3.8'
services:
  frontend:
    image: my-frontend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - REACT_APP_BACKEND_URL=http://localhost:8000
  backend:
    image: my-backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
